
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SaMsEn
 */
public class busroute extends javax.swing.JFrame {

    private Connection connection;
    /**
     * Creates new form busroute
     */
    public busroute() {
        initComponents();
        connection=dbcon.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        f = new javax.swing.JTextField();
        to = new javax.swing.JTextField();
        doj = new javax.swing.JTextField();
        dep = new javax.swing.JTextField();
        o = new javax.swing.JRadioButton();
        w = new javax.swing.JRadioButton();
        cls = new javax.swing.JTextField();
        nop = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("From");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 71, 61, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("To");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 111, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Date of Journey");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 151, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Departure");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 191, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Way Type");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 231, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Class");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 39, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("No. of Passangers");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 350, -1, -1));
        getContentPane().add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 300, -1));

        to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toActionPerformed(evt);
            }
        });
        getContentPane().add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 300, -1));
        getContentPane().add(doj, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 300, -1));
        getContentPane().add(dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 300, -1));

        o.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        o.setText("One Way");
        getContentPane().add(o, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        w.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        w.setText("Two Way");
        getContentPane().add(w, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));
        getContentPane().add(cls, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 290, -1));

        nop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopActionPerformed(evt);
            }
        });
        getContentPane().add(nop, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 290, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Bus Route");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 118, -1));

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nopActionPerformed

    private void toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String from=f.getText().toString();
        String t=to.getText().toString();
        String dat=doj.getText().toString();
        String depr=dep.getText().toString();
        String clas=cls.getText().toString();
        String p=nop.getText().toString();
        String g=(o.isSelected())?"One Way":"Two Way";
        if(from.equals(""))
        {
            JOptionPane.showMessageDialog(null," FROM SOURCE IS MANDATORY.");
        }
        else if(!from.matches("[a-zA-Z]+"))
        {
            JOptionPane.showMessageDialog(null,"FROM ONLY CONTAINS ALPHABETIC CHARACTERS.");
        }
        if(t.equals(""))
        {
            JOptionPane.showMessageDialog(null," DESTINATION SOURCE IS MANDATORY.");
        }
        else if(!t.matches("[a-zA-Z]+"))
        {
            JOptionPane.showMessageDialog(null,"DESTINATION ONLY CONTAINS ALPHABETIC CHARACTERS.");
        }
        if(dat.equals("")||!dat.equals("[0-9]+"))
        {
            JOptionPane.showMessageDialog(null,"DATE IS MANDATORY.");
        }
        if (o.isSelected() || w.isSelected()) {
            g=o.getText();
            g=w.getText();
   JOptionPane.showMessageDialog(null, "The checkbox is selected.");
} else {
   JOptionPane.showMessageDialog(null, "The checkbox is not selected.");
}
        if(clas.equals("")||!clas.matches("[a-zA-Z]+"))
        {
            JOptionPane.showMessageDialog(null," Class ONLY CONTAINS ALPHABETIC CHARACTERS ALSO MANDATORY.");
        }
        
        if(p.equals(""))
        {
            JOptionPane.showMessageDialog(null," Please Enter The number of passengers.");
        }
        else if(!p.matches("[0-9]+"))
        {
            JOptionPane.showMessageDialog(null,"Number of passengers ONLY CONTAINS NUMERIC CHARACTERS.");
        }
        Float b;
        b=Float.valueOf(nop.getText());
                        if(b.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter The number of passengers.");
        }
        else
                        {
                            try{
                            String query = "INSERT INTO bus_routes (from_location, to_location, date_of_journey, departure, way_type, class, num_of_passengers) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement preparedStatement = connection.prepareStatement(query);
            preparedStatement.setString(1, from);
            preparedStatement.setString(2, t);
            preparedStatement.setString(3, dat);
            preparedStatement.setString(4, depr);
            preparedStatement.setString(5, g);
            preparedStatement.setString(6, clas);
            preparedStatement.setString(7, p);

            int rowsAffected = preparedStatement.executeUpdate();
            if (rowsAffected > 0) {
                System.out.println("Data inserted successfully.");
            } else {
                System.out.println("Failed to insert data.");
            }

            

        } catch (SQLException e) {
            e.printStackTrace();
        }
                            
                            
                            
                            
                            
                            JOptionPane.showMessageDialog(null,"INFO SAVED SUCCESSFULLY.");
                        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new welcome().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(busroute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(busroute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(busroute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(busroute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new busroute().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField cls;
    public javax.swing.JTextField dep;
    public javax.swing.JTextField doj;
    private javax.swing.JTextField f;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField nop;
    private javax.swing.JRadioButton o;
    public javax.swing.JTextField to;
    private javax.swing.JRadioButton w;
    // End of variables declaration//GEN-END:variables
}
