/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SaMsEn
 */
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import javax.swing.JOptionPane;
public class busroute extends javax.swing.JFrame {

    /**
     * Creates new form busroute
     */
    public String travelClass,numOfPassengers;
    public int numPassengers;
    public busroute() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        departureTextField = new javax.swing.JTextField();
        oneWayRadioButton = new javax.swing.JRadioButton();
        twoWayRadioButton = new javax.swing.JRadioButton();
        travelClassTextField = new javax.swing.JTextField();
        numOfPassengersTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        fromTextField = new javax.swing.JTextField();
        toTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Class");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 80, -1));

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("From");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 81, 60));

        jLabel9.setFont(new java.awt.Font("Mistral", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("BUS ROUTE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 160, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("Next");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 80, 30));

        jLabel3.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date of Journey");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("To");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Departure");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ticket Type");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. of Passangers");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));
        jPanel1.add(departureTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 300, -1));

        oneWayRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        oneWayRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        oneWayRadioButton.setText("One Way");
        jPanel1.add(oneWayRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        twoWayRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        twoWayRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        twoWayRadioButton.setText("Two Way");
        jPanel1.add(twoWayRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 255, -1, 20));
        jPanel1.add(travelClassTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 290, -1));

        numOfPassengersTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOfPassengersTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(numOfPassengersTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 290, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 160, 10));
        jPanel1.add(fromTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 300, -1));

        toTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(toTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 300, -1));
        jPanel1.add(dateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 300, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\cool\\Downloads\\busreservationsys\\busreservationsys\\src\\main\\java\\BR.jpg")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numOfPassengersTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numOfPassengersTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numOfPassengersTextFieldActionPerformed

    private void toTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          payment p = new payment();
          p.jLabel5.setText(fromTextField.getText());
          p.jLabel9.setText(toTextField.getText());
          p.jLabel10.setText(dateTextField.getText());
          p.jLabel11.setText(departureTextField.getText());
          p.jLabel13.setText(travelClassTextField.getText());
          p.jLabel2.setText(numOfPassengersTextField.getText());
          
          p.setVisible(true);
          
    // Get input from the text fields
                                             
    // Create an instance of the busroute class
    busroute route = new busroute();
     
    // Get input from the text fields
    String from = fromTextField.getText();
    String to = toTextField.getText();
    String date = dateTextField.getText();
    String departure = departureTextField.getText();
    String ticketType = "";
    
    if (oneWayRadioButton.isSelected()) {
        ticketType = "One Way";
    } else if (twoWayRadioButton.isSelected()) {
        ticketType = "Two Way";
    }
    String travelClass = travelClassTextField.getText();
    numOfPassengers = numOfPassengersTextField.getText();
    
    numPassengers = Integer.parseInt(numOfPassengers);
    int total = 0;
    if(travelClass =="AC"|| travelClass == "ac"){
    total=total + 100;
    } else{
    total= numPassengers*100+ total;
    
    }p.jLabel15.setText("TOTAL :"+total);
    try (FileWriter writer = new FileWriter("route.txt", true)) {
        writer.write(from + " " + to + " " + date + " " + departure + " " + ticketType + " " + travelClass + " " + numOfPassengers);
        writer.write(System.lineSeparator());
        writer.flush();
        JOptionPane.showMessageDialog(this, "Route details saved successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error saving route details: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
route.numOfPassengersTextField =numOfPassengersTextField;
route.travelClassTextField =travelClassTextField;
    // Set the values of the variables in the busroute instance
    


        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(busroute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(busroute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(busroute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(busroute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new busroute().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextField departureTextField;
    private javax.swing.JTextField fromTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField numOfPassengersTextField;
    private javax.swing.JRadioButton oneWayRadioButton;
    private javax.swing.JTextField toTextField;
    public javax.swing.JTextField travelClassTextField;
    private javax.swing.JRadioButton twoWayRadioButton;
    // End of variables declaration//GEN-END:variables
}
